version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=Products

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    image: api-server
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017/Products
    networks:
      - app-network
    ports:
      - "3000:3000"


networks:
  app-network:
    driver: bridge